MADMAC=$(JAGPATH)/bin/mac
CC=m68k-atari-mint-gcc
AR=m68k-atari-mint-ar

DOXYGEN=doxygen

INCL=

MACFLAGS=-fb -v
CFLAGS=-mcpu=68000 -Wall -fomit-frame-pointer -O2 -msoft-float $(INCL)

TARGET=$(JAGPATH)/lib
