JAGPATH?=$(JAGTOOLS)
CROSSPATH?=$(M68KTOOLS)/m68k-aout

MADMAC=$(JAGPATH)/bin/mac
CC=$(CROSSPATH)/bin/gcc
AR=$(CROSSPATH)/bin/ar

DOXYGEN=doxygen

MACFLAGS=-fb -v
CFLAGS=-mc68000 -Wall -fomit-frame-pointer -O2 -msoft-float 

TARGET=$(HOME)/tmp/jlibc
